export const COLOR_SWATCH_MAP = {
  'Pearl White': '#f5f5f5',
  'Midnight Black': '#212121',
  'Titanium Silver': '#c0c0c0',
  'Ocean Blue': '#1976d2',
  'Crimson Red': '#c62828',
  'Graphite Grey': '#616161',
  'Ivory White': '#fff8e1',
  'Forest Green': '#2e7d32',
};

export const CUSTOMER_STATUS_OPTIONS = [
  { value: 'all', label: 'All Status' },
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
];

export const TRANSMISSION_OPTIONS = [
  { value: '', label: 'Select' },
  { value: 'automatic', label: 'Automatic' },
  { value: 'manual', label: 'Manual' },
];

export const FUEL_TYPE_OPTIONS = [
  { value: 'petrol', label: 'Petrol' },
  { value: 'diesel', label: 'Diesel' },
];

export const SALES_LABEL_OPTIONS = [
  { value: '', label: 'Select' },
  { value: 'company_sold', label: 'Company Sold' },
  { value: 'imported', label: 'Imported' },
  { value: 'outside_vehicle', label: 'Outside Vehicle' },
];

export function getModelYearOptions() {
  const currentYear = new Date().getFullYear();
  const startYear = 2015;
  return Array.from({ length: currentYear - startYear + 1 }, (_, i) => {
    const year = currentYear - i;
    return { value: String(year), label: String(year) };
  });
}

export const INITIAL_SALES_DATA = [
  {
    id: '1',
    salesDataId: 'SD-001',
    customerName: 'Ahmed Al-Rashid',
    customerContactNumber: '+96551234567',
    vehicleId: 'VH-006',
    vehicleName: 'JETOUR X70 Plus',
    vin: 'LGWEF4A58NS123456',
    modelYear: '2024',
    variantName: 'Premium',
    color: 'Pearl White',
    lastServiceDate: '2024-01-15',
    lastRecordedMileage: '12500',
    transmission: 'automatic',
    fuelType: 'petrol',
    salesLabel: 'company_sold',
  },
  {
    id: '2',
    salesDataId: 'SD-002',
    customerName: 'Fatima Hassan',
    customerContactNumber: '+96598765432',
    vehicleId: 'VH-003',
    vehicleName: 'JETOUR Dashing',
    vin: 'LGWEF4A59NS234567',
    modelYear: '2024',
    variantName: 'Sport',
    color: 'Midnight Black',
    lastServiceDate: null,
    lastRecordedMileage: '8500',
    transmission: 'automatic',
    fuelType: 'petrol',
    salesLabel: 'company_sold',
  },
  {
    id: '3',
    salesDataId: 'SD-003',
    customerName: 'Omar Khalid',
    customerContactNumber: '+96555667788',
    vehicleId: 'VH-004',
    vehicleName: 'JETOUR X70',
    vin: 'LGWEF4A5XNS345678',
    modelYear: '2023',
    variantName: 'Standard',
    color: 'Titanium Silver',
    lastServiceDate: '2023-11-20',
    lastRecordedMileage: '22000',
    transmission: 'manual',
    fuelType: 'petrol',
    salesLabel: 'imported',
  },
  {
    id: '4',
    salesDataId: 'SD-004',
    customerName: 'Sara Al-Mahmoud',
    customerContactNumber: '+96522334455',
    vehicleId: 'VH-002',
    vehicleName: 'JETOUR T2',
    vin: 'LGWEF4A51NS456789',
    modelYear: '2024',
    variantName: 'Adventure',
    color: 'Ocean Blue',
    lastServiceDate: '2024-02-01',
    lastRecordedMileage: '3200',
    transmission: 'automatic',
    fuelType: 'diesel',
    salesLabel: 'company_sold',
  },
  {
    id: '5',
    salesDataId: 'SD-005',
    customerName: 'Youssef Ibrahim',
    customerContactNumber: '+96577889900',
    vehicleId: 'VH-006',
    vehicleName: 'JETOUR X70 Plus',
    vin: 'LGWEF4A52NS567890',
    modelYear: '2024',
    variantName: 'Luxury',
    color: 'Crimson Red',
    lastServiceDate: null,
    lastRecordedMileage: '15000',
    transmission: 'automatic',
    fuelType: 'petrol',
    salesLabel: 'company_sold',
  },
  {
    id: '6',
    salesDataId: 'SD-006',
    customerName: 'Layla Mohammed',
    customerContactNumber: '+96533445566',
    vehicleId: 'VH-006',
    vehicleName: 'JETOUR X70 Plus',
    vin: 'LGWEF4A53NS678901',
    modelYear: '2023',
    variantName: 'Premium',
    color: 'Graphite Grey',
    lastServiceDate: '2023-09-10',
    lastRecordedMileage: '18500',
    transmission: 'automatic',
    fuelType: 'diesel',
    salesLabel: 'outside_vehicle',
  },
  {
    id: '7',
    salesDataId: 'SD-007',
    customerName: 'Khalid Al-Sayed',
    customerContactNumber: '+96566778899',
    vehicleId: 'VH-003',
    vehicleName: 'JETOUR Dashing',
    vin: 'LGWEF4A54NS789012',
    modelYear: '2024',
    variantName: 'Elite',
    color: 'Ivory White',
    lastServiceDate: '2024-03-05',
    lastRecordedMileage: '4200',
    transmission: 'automatic',
    fuelType: 'petrol',
    salesLabel: 'company_sold',
  },
  {
    id: '8',
    salesDataId: 'SD-008',
    customerName: 'Nadia Al-Farsi',
    customerContactNumber: '+96511223344',
    vehicleId: 'VH-002',
    vehicleName: 'JETOUR T2',
    vin: 'LGWEF4A55NS890123',
    modelYear: '2024',
    variantName: 'Standard',
    color: 'Forest Green',
    lastServiceDate: null,
    lastRecordedMileage: '7800',
    transmission: 'manual',
    fuelType: 'diesel',
    salesLabel: 'imported',
  },
];
