export const INITIAL_PACKAGES = [
  {
    id: 'PKG-001',
    name: 'Free Service',
    offerings: [
      'Complimentary vehicle inspection',
      'Fluid levels check',
      'Tire pressure check',
      'Exterior wash',
    ],
    priceT2: 0,
    priceT1: 0,
    mileageIntervals: [1500],
  },
  {
    id: 'PKG-002',
    name: 'M1 - Basic Maintenance',
    offerings: [
      'Engine oil change',
      'Oil filter replacement',
      'Basic vehicle inspection',
      'Tire pressure check',
    ],
    priceT2: 45,
    priceT1: 45,
    mileageIntervals: [10000, 50000, 70000, 110000],
  },
  {
    id: 'PKG-003',
    name: 'M2 - Standard Maintenance',
    offerings: [
      'Engine oil change',
      'Oil filter replacement',
      'Brake system inspection',
      'All fluid top-up',
      'Tire rotation',
      'Battery health check',
    ],
    priceT2: 75,
    priceT1: 70,
    mileageIntervals: [20000],
  },
  {
    id: 'PKG-004',
    name: 'M3 - Intermediate Maintenance',
    offerings: [
      'Engine oil change',
      'Oil filter replacement',
      'Air filter replacement',
      'Cabin filter replacement',
      'Spark plug inspection',
      'Basic vehicle inspection',
    ],
    priceT2: 45,
    priceT1: 45,
    mileageIntervals: [30000, 90000, 100000],
  },
  {
    id: 'PKG-005',
    name: 'M4 - Major Maintenance',
    offerings: [
      'Engine oil change',
      'Oil & air filter replacement',
      'Transmission fluid change',
      'Coolant system flush',
      'Drive belt inspection',
      'Full brake inspection',
    ],
    priceT2: 80,
    priceT1: 75,
    mileageIntervals: [40000, 80000],
  },
  {
    id: 'PKG-006',
    name: 'M5 - Comprehensive Maintenance',
    offerings: [
      'Complete engine service',
      'All filters replacement',
      'All fluids replacement',
      'Brake pads inspection',
      'Belt & hose replacement',
      'Full electrical system check',
      'Complete vehicle inspection',
    ],
    priceT2: 145,
    priceT1: 140,
    mileageIntervals: [60000],
  },
];
